using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Linq;
using System.Windows;

namespace WpfApplication1
{
	/// <summary>
	/// Interaction logic for App.xaml
	/// </summary>
	public partial class App : Application
	{
	}

#region raddataform-autogenerated-fields_0
private void DataForm1_AutoGeneratingField(object sender, Telerik.Windows.Controls.Data.DataForm.AutoGeneratingFieldEventArgs e)
  {   
   var employee = this.DataForm1.CurrentItem as Employee;
   if (e.PropertyName == "FirstName")
   {
    e.DataField.Label = "First Name";
   }
   if (e.PropertyName == "Salary")
   {
    e.DataField.Description = "This is the initial salary!";
   }
   if (employee.Gender == Gender.Female)
   {
    e.DataField.Foreground = new SolidColorBrush(Colors.Purple);
   }
   else
   {
    e.DataField.Foreground = new SolidColorBrush(Colors.Blue);
   }
  }
#endregion
}
