Public Class Default_Vb


' #region radchart-how-to-add-annotations-in-chart-legend_3
InitializeComponent()
Dim series1 As New DataSeries() With { New DataPoint(40), New DataPoint(40), New DataPoint(40) }
series1.Definition = New BarSeriesDefinition()
Dim series2 As New DataSeries() With { New DataPoint(80), New DataPoint(80), New DataPoint(80) }
series2.Definition = New BarSeriesDefinition()
Dim gridline As New CustomGridLine()
gridline.YIntercept = 70
gridline.ElementStyle = TryCast(Me.Resources("CustomGridLineStyle"), Style)
RadChart1.DefaultView.ChartArea.Annotations.Add(gridline)
RadChart1.DefaultView.ChartArea.PaletteBrushes.Add(New SolidColorBrush(Colors.Gray))
RadChart1.DefaultView.ChartArea.PaletteBrushes.Add(New SolidColorBrush(Colors.Red))
RadChart1.DefaultView.ChartArea.AxisX.LayoutMode = AxisLayoutMode.Inside
RadChart1.DefaultView.ChartArea.DataSeries.Add(series1)
RadChart1.DefaultView.ChartArea.DataSeries.Add(series2)
' #endregion

' #region radchart-how-to-add-annotations-in-chart-legend_5
RadChart1.DefaultView.ChartLegend.UseAutoGeneratedItems = False
                  Dim item01 As New ChartLegendItem()
                  item01.MarkerFill = New SolidColorBrush(Colors.Gray)
                  item01.Label = "Bar Chart 1"
                  RadChart1.DefaultView.ChartLegend.Items.Add(item01)
                  Dim item02 As New ChartLegendItem()
                  item02.MarkerFill = New SolidColorBrush(Colors.Red)
                  item02.Label = "Bar Chart 2"
                  RadChart1.DefaultView.ChartLegend.Items.Add(item02)
                  Dim item2 As New ChartLegendItem()
                  item2.Label = "My CustomGridLine"
                  item2.Style = TryCast(Me.Resources("DashedLegendItem2"), Style)
                  RadChart1.DefaultView.ChartLegend.Items.Add(item2)
' #endregion
End Class
