using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Linq;
using System.Windows;

namespace WpfApplication1
{
	/// <summary>
	/// Interaction logic for App.xaml
	/// </summary>
	public partial class App : Application
	{
	}

#region radchart-how-to-add-annotations-in-chart-legend_2
InitializeComponent();
            DataSeries series1 = new DataSeries()
            {
                new DataPoint(40), 
                new DataPoint(40), 
                new DataPoint(40) 
            };
            series1.Definition = new BarSeriesDefinition();
            DataSeries series2 = new DataSeries()
            {
                new DataPoint(80), 
                new DataPoint(80), 
                new DataPoint(80) 
            };
            series2.Definition = new BarSeriesDefinition();
            CustomGridLine gridline = new CustomGridLine();
            gridline.YIntercept = 70;
            gridline.ElementStyle = this.Resources["CustomGridLineStyle"] as Style; 
            RadChart1.DefaultView.ChartArea.Annotations.Add(gridline);
            RadChart1.DefaultView.ChartArea.PaletteBrushes.Add(new SolidColorBrush(Colors.Gray));
            RadChart1.DefaultView.ChartArea.PaletteBrushes.Add(new SolidColorBrush(Colors.Red));
            RadChart1.DefaultView.ChartArea.AxisX.LayoutMode = AxisLayoutMode.Inside;
            RadChart1.DefaultView.ChartArea.DataSeries.Add(series1);
            RadChart1.DefaultView.ChartArea.DataSeries.Add(series2);
#endregion

#region radchart-how-to-add-annotations-in-chart-legend_4
RadChart1.DefaultView.ChartLegend.UseAutoGeneratedItems = false;
ChartLegendItem item01 = new ChartLegendItem();
item01.MarkerFill = new SolidColorBrush(Colors.Gray);
item01.Label = "Bar Chart 1";
RadChart1.DefaultView.ChartLegend.Items.Add(item01);
ChartLegendItem item02 = new ChartLegendItem();
item02.MarkerFill = new SolidColorBrush(Colors.Red);
item02.Label = "Bar Chart 2";
RadChart1.DefaultView.ChartLegend.Items.Add(item02);
ChartLegendItem item2 = new ChartLegendItem();
item2.Label = "My CustomGridLine";
item2.Style = this.Resources["DashedLegendItem2"] as Style;
RadChart1.DefaultView.ChartLegend.Items.Add(item2);
#endregion
}
