using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Linq;
using System.Windows;

namespace WpfApplication1
{
	/// <summary>
	/// Interaction logic for App.xaml
	/// </summary>
	public partial class App : Application
	{
	}

#region radchart-getting-started-create-a-line-chart-with-static-data_2
radChart.DefaultView.ChartTitle.Content = "Year 2009";
radChart.DefaultView.ChartLegend.Header = "Legend";
radChart.DefaultView.ChartLegend.UseAutoGeneratedItems = true;
//Axis X
radChart.DefaultView.ChartArea.AxisX.Title = "Month";
radChart.DefaultView.ChartArea.AxisX.AutoRange = false;
radChart.DefaultView.ChartArea.AxisX.MinValue = 1;
radChart.DefaultView.ChartArea.AxisX.MaxValue = 12;
radChart.DefaultView.ChartArea.AxisX.Step = 1;
radChart.DefaultView.ChartArea.AxisX.LayoutMode = AxisLayoutMode.Between;
//Axis Y
radChart.DefaultView.ChartArea.AxisY.Title = "Quantity";
DataSeries series = new DataSeries();
series.Definition = new LineSeriesDefinition();
series.LegendLabel = "Product Sales";
series.Add( new DataPoint( 1, 154 ) );
series.Add( new DataPoint( 2, 138 ) );
series.Add( new DataPoint( 3, 143 ) );
series.Add( new DataPoint( 4, 120 ) );
series.Add( new DataPoint( 5, 135 ) );
series.Add( new DataPoint( 6, 125 ) );
series.Add( new DataPoint( 7, 179 ) );
series.Add( new DataPoint( 8, 170 ) );
series.Add( new DataPoint( 9, 198 ) );
series.Add( new DataPoint( 10, 187 ) );
series.Add( new DataPoint( 11, 193 ) );
series.Add( new DataPoint( 12, 212 ) );
radChart.DefaultView.ChartArea.DataSeries.Add( series );
#endregion
}
