Public Class Default_Vb


' #region radchart-features-axes-striplines-and-gridlines_2
' Left Chart
radChart.DefaultView.ChartLegend.UseAutoGeneratedItems = True
radChart.DefaultView.ChartLegend.Visibility = Visibility.Collapsed
radChart.DefaultView.ChartArea.AxisX.StripLinesVisibility = Visibility.Visible
radChart.DefaultView.ChartArea.AxisY.StripLinesVisibility = Visibility.Collapsed
radChart.DefaultView.ChartArea.AxisY.MajorGridLinesVisibility = Visibility.Collapsed
radChart.DefaultView.ChartArea.AxisY.MinorGridLinesVisibility = Visibility.Visible
' Right Chart
radChart.DefaultView.ChartArea.AxisX.MajorGridLinesVisibility = Visibility.Visible
radChart.DefaultView.ChartArea.AxisY.StripLinesVisibility = Visibility.Collapsed
radChart.DefaultView.ChartArea.AxisY.MajorGridLinesVisibility = Visibility.Visible
radChart.DefaultView.ChartArea.AxisY.MinorGridLinesVisibility = Visibility.Collapsed
radChart.DefaultView.ChartArea.AxisX.LayoutMode = AxisLayoutMode.Inside
' #endregion
End Class
