using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Linq;
using System.Windows;

namespace WpfApplication1
{
	/// <summary>
	/// Interaction logic for App.xaml
	/// </summary>
	public partial class App : Application
	{
	}

#region radtilelist-autogenerated-tiles_0
    public class Employee
    {
        public string FirstName
        {
            get;
            set;
        }
        public string LastName
        {
            get;
            set;
        }
        public string Occupation
        {
            get;
            set;
        }
        public int Salary
        {
            get;
            set;
        }
    }
#endregion
    #region radtilelist-autogenerated-tiles_2
    public class Employee
    {

        public Employee()
        { }

        public static ObservableCollection<Employee> GetEmployees()
        {
            ObservableCollection<Employee> employees = new ObservableCollection<Employee>();
            employees.Add(new Employee() { FirstName = "Sarah", LastName = "Blake", Occupation = "Suppliess Manager", Salary = 3500 });
            employees.Add(new Employee() { FirstName = "Jane", LastName = "Simpson", Occupation = "Security", Salary = 2000 });
            employees.Add(new Employee() { FirstName = "John", LastName = "Peterson", Occupation = "Consultant", Salary = 2600 });
            employees.Add(new Employee() { FirstName = "Peter", LastName = "Bush", Occupation = "Cashier", Salary = 2300 });
            return employees;
        }
    }
    #endregion
     #region radtilelist-autogenerated-tiles_4
    public MainPage()
  {
   InitializeComponent();   
   this.RadTileList.ItemsSource = Employee.GetEmployees();
  }
     #endregion
     #region radtilelist-autogenerated-tiles_7
    private void RadTileList_AutoGeneratingTile(object sender, AutoGeneratingTileEventArgs e)
        {
            Employee employee = e.Tile.Content as Employee;
            if (employee.FirstName == "Jane")
            {
                e.Tile.Content = new TextBlock {Text=employee.FirstName };
                e.Tile.Background = new SolidColorBrush(Colors.Blue);
                e.Tile.TileType = TileType.Single;
            }
        }
     #endregion

}
