using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Linq;
using System.Windows;

namespace WpfApplication1
{
	/// <summary>
	/// Interaction logic for App.xaml
	/// </summary>
	public partial class App : Application
	{
	}

#region radpropertygrid-getting-started-autogenerated-property-definitions_0
private void PropertyGrid1_AutoGeneratingPropertyDefinition(object sender, Telerik.Windows.Controls.Data.PropertyGrid.AutoGeneratingPropertyDefinitionEventArgs e)
  {   
   if(e.PropertyDefinition.DisplayName == "Background")
   {
    e.PropertyDefinition.Description = "This property displays the background property of the RadButton";       
   }
  }
#endregion
}
