Public Class Default_Vb


' #region radpropertygrid-getting-started-autogenerated-property-definitions_1
Private Sub PropertyGrid1_AutoGeneratingPropertyDefinition(sender As Object, e As Telerik.Windows.Controls.Data.PropertyGrid.AutoGeneratingPropertyDefinitionEventArgs)
 If e.PropertyDefinition.DisplayName = "Background" Then
  e.PropertyDefinition.Description = "This property displays the background property of the RadButton"
 End If
End Sub
' #endregion
End Class
