using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Linq;
using System.Windows;

namespace WpfApplication1
{
	/// <summary>
	/// Interaction logic for App.xaml
	/// </summary>
	public partial class App : Application
	{
	}

#region radchart-features-chart-legend_1
radChart.DefaultView.ChartLegend.UseAutoGeneratedItems = true;
radChart.DefaultView.ChartLegend.Header = "Top 10 Manufacturers";
#endregion

#region radchart-features-chart-legend_4
Telerik.Windows.Controls.RadChart radChart = new Telerik.Windows.Controls.RadChart();
radChart.DefaultView.ChartLegend.UseAutoGeneratedItems = false;
ChartLegendItem item1 = new ChartLegendItem();
item1.Label = "Item 1";
item1.MarkerFill = new SolidColorBrush( Colors.Blue );
radChart.DefaultView.ChartLegend.Items.Add( item1 );
ChartLegendItem item2 = new ChartLegendItem();
item2.Label = "Item 2";
item2.MarkerFill = new SolidColorBrush( Colors.Green );
radChart.DefaultView.ChartLegend.Items.Add( item2 );
#endregion

#region radchart-features-chart-legend_6
public LegendDisplayModeSample()
{
    InitializeComponent();
    this.radChart.ItemsSource = new int[] { 1, 5, 6, 9, 5, 7 };
    this.radChart.DefaultSeriesDefinition.LegendDisplayMode = LegendDisplayMode.SeriesLabel;
}
#endregion

#region radchart-features-chart-legend_8
this.radChart.DefaultView.ChartLegendPosition = Dock.Bottom;
#endregion

#region radchart-features-chart-legend_10
this.radChart.DefaultView.ChartLegend.LegendItemMarkerShape = MarkerShape.StarFiveRay;
#endregion
}
