Public Class Default_Vb


' #region radchart-features-chart-legend_2
radChart.DefaultView.ChartLegend.UseAutoGeneratedItems = true
radChart.DefaultView.ChartLegend.Header = "Top 10 Manufacturers"
' #endregion

' #region radchart-features-chart-legend_5
Dim radChart As New Telerik.Windows.Controls.RadChart()
radChart.DefaultView.ChartLegend.UseAutoGeneratedItems = False
Dim item1 As New ChartLegendItem()
item1.Label = "Item 1"
item1.MarkerFill = New SolidColorBrush( Colors.Blue )
radChart.DefaultView.ChartLegend.Items.Add( item1 )
Dim item2 As New ChartLegendItem()
item2.Label = "Item 2"
item2.MarkerFill = New SolidColorBrush( Colors.Green )
radChart.DefaultView.ChartLegend.Items.Add( item2 )
' #endregion

' #region radchart-features-chart-legend_7
Public Sub New()
 InitializeComponent()
 Me.radChart.ItemsSource = New Integer() {1, 5, 6, 9, 5, 7}
 Me.radChart.DefaultSeriesDefinition.LegendDisplayMode = LegendDisplayMode.SeriesLabel
End Sub
' #endregion

' #region radchart-features-chart-legend_9
Me.radChart.DefaultView.ChartLegendPosition = Dock.Bottom
' #endregion

' #region radchart-features-chart-legend_11
Me.radChart.DefaultView.ChartLegend.LegendItemMarkerShape = MarkerShape.StarFiveRay
' #endregion
End Class
